### PR TITLE
Use python runtime directory for python modules.

### PR DESCRIPTION
**Pull request by lucc**
Vim already provides some special directories in sys.path so nothing needs to
be added manually.  See `:help python2-directory` for more.  This reduces the
setup logic for the plugin a little.

### CODE REVIEW

**Comment by lucc** [comment]
I just did some more tests and it might be better to use the pythonx directory (I get some import errors). Did you notice anything?

**Comment by guyzmo** [comment]
I haven't tested this yet, I'm currently burried in work. 

I'm reverting the PR and please make sure it works fine by squashing your current branch.

**Comment by lucc** [comment]
Sorry to answer so late. I just did some tests again and it seems that my import errors where due to the plugin being installed two times.

I tried again with this shell command:
```sh
vim -u /dev/null --cmd 'set nocompatible' --cmd "set rtp^=$PWD" '+if InitAddressBook()==0 | q | endif' +cq
```
And I don't get any errors and also an exit code of 0.

My conclusion is that this was reverted prematurely. Maybe you can have a closer look when you have time.

**Comment by guyzmo** [comment]
ok, need to look at all that again

**Comment by lucc** [comment]
I rebased my changes on the current master and pushed them to https://github.com/lucc/notmuch-abook/tree/python-dir.

**Comment by guyzmo** [comment]
merged again ;-)

thank you

**Pull request merged**
